stages:
  stage_01:
    cmd: python stage_1.py
    deps: 
      - stage_1.py
    outs :
      - file_1.txt
    


  stage_02:
    cmd: python stage_2.py
    deps: 
      - file_1.txt
      - stage_1.py
  
  stage_03:
    cmd: python stage_3.py
    deps: 
      - stage_1.py
      - file_1.txt

